WebProject2017/Models/ProfilViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebProject2017Server.Modèle;

namespace WebProject2017.Models
{
    public class ProfilViewModel
    {
        public User User { get; set; }
        public List<Journey> Journeys { get; set; }

    }
}

WebProject2017/Models/SearchJourneyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebProject2017Server.Modèle;

namespace WebProject2017.Models
{
    public class SearchJourneyViewModel
    {
        public List<Journey> Result { get; set; }
        public List<Journey> JourneysUser { get; set; }
    }
}

WebProject2017/Models/SignInModelView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebProject2017.Models
{
    public class SignInModelView
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Le login est invalide")]
        public string Login { get; set; }
        [DataType(DataType.Password)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Le mot de passe est invalide")]
        public string Password { get; set; }
    }
}

WebProject2017/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebProject2017.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Welcome()
        {
            return View();
        }
    }
}

WebProject2017/Controllers/JourneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using WebProject2017.Models;
using WebProject2017Server.EF.Mappers;
using WebProject2017Server.Modèle;

namespace WebProject2017.Controllers
{
    public class JourneyController : Controller
    {
        // GET: Journey
        public ActionResult SearchJourney()
        {
            SearchJourneyViewModel model = new SearchJourneyViewModel();
            model.Result = new List<Journey>();
            using(EFJourneyMapper mapper = new EFJourneyMapper("WebProject2017-DBb"))
            {               
                model.Result = mapper.GetAll();               
               
            }
            model.JourneysUser = new List<Journey>();
            if (((User)Session["User"]) != null)
            {
                foreach (Journey j in model.Result)
                {
                    if (j.Driver.ID == ((User)Session["User"]).ID)
                    {
                        model.JourneysUser.Add(j);
                    }
                }
            }
            return View(model);
        }
        public ActionResult AddJourney()
        {
            if (((User)Session["User"]) != null)
            {
                return View();
            }
            return RedirectToAction("Sign_In_Out","Users");
        }
        // POST: JOURNEY
        [HttpPost]
        public ActionResult AddJourney(Journey journey)
        {
            if (ModelState.IsValid)
            {
                using (EFJourneyMapper mapper = new EFJourneyMapper("WebProject2017-DBb"))
                {
                    try
                    {
                        journey.Driver = (User)Session["User"];
                        journey = mapper.AddorUpdate(journey);
                        return RedirectToAction("Profil","Users");
                    }
                    catch (Exception ex)
                    {
                        ViewBag.MessageErreur = ex.Message;
                    }
                }
            }
            return View(journey);
        }
        [HttpPost]
        public ActionResult Profil(SearchJourneyViewModel model)
        {            
            return View(model);
        }
    }
}

WebProject2017/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using WebProject2017.Models;
using WebProject2017Server.EF.Mappers;
using WebProject2017Server.Modèle;

namespace WebProject2017.Controllers
{
    public class UsersController : Controller
    {
       
        // GET
        public ActionResult Profil()
        {
            if (((User)Session["User"]) != null)
            {
                ProfilViewModel vm;
                using (EFUserMapper mapper = new EFUserMapper("WebProject2017-DBb"))
                {
                    vm = new ProfilViewModel()
                    {
                        User = mapper.FindBy(((User)Session["User"]).ID),
                        Journeys = new List<Journey>()
                    };
                }
                return View(vm);
            }
            else
            {
                return RedirectToAction("Sign_In_Out");
            }            
        }
        public ActionResult Sign_In_Out()
        {
            return View(new SignInModelView() { Login = "login", Password = "12345" });
        }
        public ActionResult Sign_Up()
        {
            return View(new User() { Login = "login", Password = "12345", LastName = "bologne", Name = "sauce", Email = "email@gamil.com", Phone = "0475859565" });
        }
        public ActionResult ProfilEditor()
        {
            User user;
            using (EFUserMapper mapper = new EFUserMapper("WebProject2017-DBb"))
            {
                user = mapper.FindBy(((User)Session["User"]).ID);
            }
            return View(user);
        }
        public ActionResult AddressEditor()
        {
            User user;
            using (EFUserMapper mapper = new EFUserMapper("WebProject2017-DBb"))
            {
                user = mapper.FindBy(((User)Session["User"]).ID);
            }
            return View(user.Address);
        }

        //Post
        [HttpPost]
        public ActionResult Sign_In_Out(SignInModelView user)
        {
 
            if (ModelState.IsValid)
            {
                using (EFUserMapper mapper = new EFUserMapper("WebProject2017-DBb"))
                {
                    Expression<Func<User, bool>> expression = u => u.Login == user.Login && u.Password == user.Password;
                    List<User> uss = mapper.FindBy(expression).ToList<User>();

                    if (uss.Count > 0)
                    {
                        User us = uss.First();
                        Session.Add("User", us);
                        return RedirectToAction("Profil");
                    }
                    else
                    {
                        ViewBag.MessageErreur = "idenfiant incorrect";
                    }
                }
            }
            return View();
        }
        [HttpPost]
        public ActionResult Sign_Up(User user)
        {
            
            if (ModelState.IsValid)
            {
                using (EFUserMapper mapper = new EFUserMapper("WebProject2017-DBb"))
                {
                    try
                    {
                        user = mapper.AddorUpdate(user);
                        Session.Add("User", user);
                        return RedirectToAction("Profil");
                    }
                    catch(Exception ex)
                    {
                        ViewBag.MessageErreur = ex.Message;
                    }
                }
            }
            return View(user);
        }
        [HttpPost]
        public ActionResult Profil(ProfilViewModel model)
        {

            return RedirectToAction("ProfilEditor", new { user = (User)model.User }); ;
        }
        [HttpPost]
        public ActionResult Profila(ProfilViewModel model)
        {

            return RedirectToAction("AddressEditor", new { user = (User)model.User }); ;
        }
        [HttpPost]
        public ActionResult ProfilEditor(User user)
        {
            
            if (ModelState.IsValid)
            {
                using (EFUserMapper mapper = new EFUserMapper("WebProject2017-DBb"))
                {
                    user.ID = (int)Session["UserId"];
                    mapper.AddorUpdate(user);
                    return RedirectToAction("Profil");
                }
            }
            return View(user);
        }

    }
}

WebProject2017/Views/Home/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
}

<h2 class="col-12 col-m-12">Accueil</h2>

<div class="col-9 col-m-12">
    <h3>The City</h3>
    <p>Chania is the capital of the Chania region on the island of Crete. The city can be divided in two parts, the old town and the modern city.</p>
    <p>Resize the browser window to see how the content respond to the resizing.</p>
</div>

WebProject2017/Views/Journey/AddJourney.cshtml
@model WebProject2017Server.Modèle.Journey

@{
    ViewBag.Title = "AddJourney";
}
<h2>Ajouté Trajet</h2>

@using (Html.BeginForm("AddJourney", "Journey", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    @Html.ValidationSummary()
    <div class="groupForm col-">
        <label class="labelForm">Description : </label>
        @Html.EditorFor(model => model.Description)
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Nombre de place(s) Disponible(S) : </label>
        @Html.EditorFor(model => model.FreeSeat)
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Prix par siège : </label>
        @Html.EditorFor(model => model.Price, new { type = "number", min = "0", step = "0.01" })
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Départ : </label>
        @Html.EditorFor(model => model.StartingDateTime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Arrivé : </label>
        @Html.EditorFor(model => model.DriverUpDatetime, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
    </div>
    <div class="col-6">
        <h3>Address de Départ</h3>
        <div class="groupForm col-">
            <label class="labelForm">Pays : </label>
            @Html.EditorFor(model => model.StartingAddress.Country)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Localité : </label>
            @Html.EditorFor(model => model.StartingAddress.Locality)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Code Postal : </label>
            @Html.EditorFor(model => model.StartingAddress.PostalCode)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Rue : </label>
            @Html.EditorFor(model => model.StartingAddress.Road)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Numéro : </label>
            @Html.EditorFor(model => model.StartingAddress.Number)
        </div>
    </div>
    <div class="col-6">
        <h3>Address d'arrivé</h3>
        <div class="groupForm col-">
            <label class="labelForm">Pays : </label>
            @Html.EditorFor(model => model.DriverUpAddress.Country)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Localité : </label>
            @Html.EditorFor(model => model.DriverUpAddress.Locality)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Code Postal : </label>
            @Html.EditorFor(model => model.DriverUpAddress.PostalCode)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Rue : </label>
            @Html.EditorFor(model => model.DriverUpAddress.Road)
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Numéro : </label>
            @Html.EditorFor(model => model.DriverUpAddress.Number)
        </div>
    </div>
    <div class="groupForm">
        <input class="btn col-" type="submit" id="SendSearch" value="Valider" />
    </div>
}

WebProject2017/Views/Journey/SearchJourney.cshtml
@model WebProject2017.Models.SearchJourneyViewModel
@{
    ViewBag.Title = "JourneySearch";
}

<h3>Trajet</h3>

<section class="col-6 col-m-8">
    <h4>Recherche</h4>
    <form>
        <div class="groupForm">
            <label class="labelForm">Départ : </label>
            <input type="search" name="JourneyStart" />
        </div>
        <div class="groupForm">
            <label class="labelForm">Arrivé : </label>
            <input type="search" name="JourneyArrival" />
        </div>
        <div class="groupForm">
            <input class="btn" type="button" id="StartArrivalDate" value="Départ" onclick="changeValue('Départ','Arrivée')" />
            <input type="datetime-local" name="JourneyDate" />
        </div>
        <div class="groupForm col-">
            <input class="btn col-" type="submit" id="SendSearch" value="Recherche" />
        </div>
    </form>
    <div>
        <h5>Résultats :</h5>
        @foreach (var item in Model.Result)
        {
            using (Html.BeginForm("Profil", "Journey", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
            {
                <div class="journey col-6 col-m-12">
                    <label class="col-6 col-m-12" id="Start">Départ : @item.StartingDateTime : @item.StartingAddress.Locality</label>
                    <span>--></span>
                    <label class="col-6 col-m-12" id="Arrival">Arrivé : @item.DriverUpDatetime : @item.DriverUpAddress.Locality</label>
                    <label class="nbrSeat" id="nbrSeat">@item.FreeSeat place(s)</label>
                    <label class="price" id="nbrSeat">@item.Price €</label>
                    <input class="btn btn-bis col-" type="submit" id="SendSearch" value="Voyager" />
                </div>
            }
        }

    </div>
</section>
<section class="col-6 col-m-4">
    <h4>Mes trajets</h4>
    <input class="btn col-" type="submit" id="SendSearch" value="Ajouter un trajet" onclick="location.href='@Url.Action("AddJourney","Journey")'" />
      
    @foreach (var item in Model.JourneysUser)
    {
        using (Html.BeginForm("Profil", "Journey", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
        {
            <div class="journey col-6 col-m-12">
                <label class="col-6 col-m-12" id="Start">Départ : @item.StartingDateTime : @item.StartingAddress.Locality</label>
                <span>--></span>
                <label class="col-6 col-m-12" id="Arrival">Arrivé : @item.DriverUpDatetime : @item.DriverUpAddress.Locality</label>
                <label class="nbrSeat" id="nbrSeat">@item.FreeSeat place(s)</label>
                <label class="price" id="nbrSeat">@item.Price €</label>
                <input class="btn btn-bis col-" type="submit" id="SendSearch" value="Editer" />
            </div>
        }
    }
</section>

WebProject2017/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/Script.js"></script>  
</head>
<body>
    <header>
        
        <h1>GoCars</h1>
        <div class=" banner" ></div>
        <nav>
            <ul>
                <li class="col-3 col-m-6"><input class="btnMenu" type="button" value="Accueil" onclick="location.href='@Url.Action("Welcome","Home")'" /></li>
                <li class="col-3 col-m-6"><input class="btnMenu" type="button" value="Coin Perso" onclick="location.href='@Url.Action("Profil","Users")'" /></li>
                <li class="col-3 col-m-6"><input class="btnMenu" type="button" value="Trajet" onclick="location.href='@Url.Action("SearchJourney","Journey")'" /></li>
                <li class="col-3 col-m-6"><input class="btnMenu" type="button" value="Connexion" onclick="location.href='@Url.Action("Sign_In_Out","Users")'" /></li>
               
            </ul>
        </nav>
    </header>
    
    @RenderBody()
    
</body>
</html>

WebProject2017/Views/Shared/_UserForm.cshtml
@model WebProject2017Server.Modèle.User

@Html.ValidationSummary()
<div class="groupForm col-">
    <label class="labelForm">Login : </label>
    @Html.EditorFor(model => model.Login)
</div>
<div class="groupForm col-">
    <label class="labelForm">Mot de passe : </label>
    @Html.EditorFor(model => model.Password)
</div>
<div class="groupForm col-">
    <label class="labelForm">Nom : </label>
    @Html.EditorFor(model => model.LastName)
</div>
<div class="groupForm col-">
    <label class="labelForm">Prénom : </label>
    @Html.EditorFor(model => model.Name)
</div>
<div class="groupForm col-">
    <label class="labelForm">téléphone : </label>
    @Html.EditorFor(model => model.Phone)
</div>
<div class="groupForm col-">
    <label class="labelForm">Email : </label>
    @Html.EditorFor(model => model.Email)
</div>

WebProject2017/Views/Users/AddressEditor.cshtml
@model WebProject2017Server.Modèle.Address
@{
    ViewBag.Title = "AddressEditor";
}

<h2>AddressEditor</h2>
@using (Html.BeginForm("AddressEditor", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    @Html.ValidationSummary()
    <div class="groupForm col-">
        <label class="labelForm">Localitier : </label>
        @Html.EditorFor(model => model.Locality)
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Code Postal : </label>
        @Html.EditorFor(model => model.PostalCode)
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Rue : </label>
        @Html.EditorFor(model => model.Road)
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Numéro : </label>
        @Html.EditorFor(model => model.Number)
    </div>
    <div class="groupForm col-">
        <input class="btn col-" type="submit" id="SendSearch" value="Valider" />
    </div>
}

WebProject2017/Views/Users/Profil.cshtml
@model WebProject2017.Models.ProfilViewModel
@{
    ViewBag.Title = "Profil";
}

<section class="col-">
    <h4>Mes trajets</h4>
    <input class="btn col-" type="submit" id="AddJ" value="Ajouter un trajet" onclick="location.href='@Url.Action("AddJourney","Journey")'"/>

    @foreach (var journey in @Model.Journeys)
    {
        <div class="journey col-6 col-m-12">
            <label id="Strat">@journey.StartingAddress _ @journey.StartingDateTime</label>
            <span>--></span>
            <label id="Arrival">@journey.DriverUpAddress _ @journey.DriverUpDatetime</label>
            <label class="nbrSeat" id="nbrSeat">X places</label>
            <input class="btn btn-bis col-" type="submit" id="SendSearch" value="Annuler" />
        </div>
    }
    <div class="journey col-6 col-m-12">
        <label id="Strat">DXXXXX_MM:HH</label>
        <span>--></span>
        <label id="Arrival">AXXXXXX_MM:HH</label>
        <label class="nbrSeat" id="nbrSeat">X place(s)</label>
        <input class="btn btn-bis col-" type="submit" id="SendSearch" value="Editer" />
    </div>
</section>
<section class="col-">
@using (Html.BeginForm("Profil", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    <h4>Mes Informations</h4>

    <div class="groupForm col-">
        <label class="labelForm">Login : </label>
        <label>@Model.User.Login</label>
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Nom : </label>
        <label>@Model.User.LastName</label>
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Prénom : </label>
        <label>@Model.User.Name</label>
    </div>
    <div class="groupForm col-">
        <label class="labelForm">téléphone : </label>
        <label>@Model.User.Phone</label>
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Email : </label>
        <label>@Model.User.Email</label>
    </div>
    <div class="groupForm col-">        
        <input class="btn btn-bis col-" type="submit" id="SendSearch" value="Modifier"/>        
    </div>

}
    @using (Html.BeginForm("Profila", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
    {
        <h4>Mon Adresse</h4>
        if (Model.User.Address != null)
        {
        <div class="groupForm col-">
            <label class="labelForm">Pays : </label>
            <label>@Model.User.Address.Country</label>
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Localiter : </label>
            <label>@Model.User.Address.Locality</label>
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Code Postal : </label>
            <label>@Model.User.Address.PostalCode</label>
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Rue : </label>
            <label>@Model.User.Address.Road</label>
        </div>
        <div class="groupForm col-">
            <label class="labelForm">Numero : </label>
            <label>@Model.User.Address.Number</label>
        </div>        
        <div class="groupForm col-">
            <input class="btn btn-bis col-" type="submit" id="SendSearch" value="Modifer adresse" />
        </div>
        }
        else
        {
            <div class="groupForm col-">
                <label class="labelForm">Pas d'adresse enregistrée</label>
            </div>
        }

    }
</section>

WebProject2017/Views/Users/ProfilEditor.cshtml
@model WebProject2017Server.Modèle.User
@{
    ViewBag.Title = "ProfilEditor";
}

<h3>ProfilEditor</h3>
@using (Html.BeginForm("ProfilEditor", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    @Html.Partial("_UserForm", @Model)
    <div class="groupForm col-">
        <input class="btn col-" type="submit" id="SendSearch" value="Valider"/>
    </div>
}

WebProject2017/Views/Users/Sign_In_Out.cshtml
@model WebProject2017.Models.SignInModelView
@{
    ViewBag.Title = "Sign_In_Out";
}

<h3>Connexion</h3>
@using (Html.BeginForm("Sign_In_Out", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    <span style="color:red">@ViewBag.MessageErreur</span>
    <div class="groupForm col-">
        <label class="labelForm">Login : </label>
        @Html.EditorFor(model => model.Login)
    </div>
    <div class="groupForm col-">
        <label class="labelForm">Mot de passe : </label>
        @Html.EditorFor(model => model.Password)
    </div>
    <div class="groupForm col-">
        <input class="btn col-" type="submit" id="SendSearch" value="Connexion" />
    </div>
    <p><br/>Pas encore de compte ? @Html.ActionLink("Inscivez-vous !!!", "Sign_Up", "Users")</p>

}

WebProject2017/Views/Users/Sign_Up.cshtml
@model WebProject2017Server.Modèle.User
@{
        ViewBag.Title = "Sign_Up";
}
<h3>Sign_Up</h3>

@using (Html.BeginForm("Sign_Up", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    <span style="color:red">@ViewBag.MessageErreur</span>

    @Html.Partial("_UserForm", @Model)
    <div class="groupForm col-">
        <input class="btn col-" type="submit" id="SendSearch" value="Valider"/>
    </div>
}